In [11]:
# math ====>>. all mathameticala cal

import math
print math.factorial(5)
print math.sqrt(25)
print math.ceil(8.99)
print math.ceil(8.0001)
print math.floor(7.9999)
print math.floor(7.00001)
print round(4.3)
print round(4.7)
print math.pi
print math.degrees(math.pi)
print math.radians(180)
print math.pow(12,3)

120
5.0
9.0
9.0
7.0
7.0
4.0
5.0
3.14159265359
180.0
3.14159265359
1728.0


In [12]:
import math
print dir(math)

['__doc__', '__name__', '__package__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'ceil', 'copysign', 'cos', 'cosh', 'degrees', 'e', 'erf', 'erfc', 'exp', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'hypot', 'isinf', 'isnan', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'modf', 'pi', 'pow', 'radians', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'trunc']


In [13]:
import math
help(math)

Help on built-in module math:

NAME
    math

FILE
    (built-in)

DESCRIPTION
    This module is always available.  It provides access to the
    mathematical functions defined by the C standard.

FUNCTIONS
    acos(...)
        acos(x)
        
        Return the arc cosine (measured in radians) of x.
    
    acosh(...)
        acosh(x)
        
        Return the inverse hyperbolic cosine of x.
    
    asin(...)
        asin(x)
        
        Return the arc sine (measured in radians) of x.
    
    asinh(...)
        asinh(x)
        
        Return the inverse hyperbolic sine of x.
    
    atan(...)
        atan(x)
        
        Return the arc tangent (measured in radians) of x.
    
    atan2(...)
        atan2(y, x)
        
        Return the arc tangent (measured in radians) of y/x.
        Unlike atan(y/x), the signs of both x and y are considered.
    
    atanh(...)
        atanh(x)
        
        Return the inverse hyperbolic tangent of x.
    
    ceil(...)
     

In [15]:
math.copysign(5,-4)

-5.0

In [18]:
import math as m
print m.factorial(5)
print m.pi
print m.sqrt(8)

120
3.14159265359
2.82842712475


In [19]:
from math import factorial,pi
print factorial(5)
print pi
print sqrt(4)

120
3.14159265359


NameError: name 'sqrt' is not defined

In [21]:
from math import *

print factorial(5)
print pi
print sqrt(4)
print radians(180)
print degrees(pi)


120
3.14159265359
2.0
3.14159265359
180.0


In [22]:
# semi predined modules and packages

import numpy


In [23]:
print numpy.array([12,45,6])

[12 45  6]


In [24]:
import numpy as np
np.array([12,45,6])

array([12, 45,  6])

In [25]:
from numpy import array
array([12,45,5])

array([12, 45,  5])